### PR TITLE
Added update threshold & some cosmetics

### PR DESCRIPTION
**Pull request by h45rd**
re-worded thresholds explanation and removed a line break in log output

### CODE REVIEW

**Comment by ryecoaaron** [comment]
A few things...
1 - You never need to edit the locale files.  They are automatically generated.
2 - The database model needs to have the new field added in confdb and datamodels in /usr/share/openmediavault/
3 - Upgrades will need to add this field to the database in a confdb migration script.

**Comment by h45rd** [comment]
D'oh.. sorry for being such a noob when it comes to the inner workings of OMV.
Thanks for taking the time to explain.

1 & 2:
Should have looked through the whole repo and not just search it for "*threshold*". 
Just learned about the restrictions concerning code search and wildcards in the github webinterface.
I will fix this.

3:
So basically the same procedure you did in 0b25e7a402411f3ebd6e8a60417b375b16292278 when switching to omv-confdbadm? Update the changelog to increment the version number and create a conf.service.snapraid_3.7.0.sh that adds the new field to the db on update?
Will try my best.

Is there a resource I can read up on OMV plugin development?


Cheers,
h45rd

**Comment by ryecoaaron** [comment]
3 - You just need to create usr/share/openmediavault/confdb/migrations.d/conf.service.snapraid_3.7.4.sh that looks a lot like https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/master/usr/share/openmediavault/confdb/migrations.d/conf.service.snapraid_3.6.3.sh

Don't worry about incrementing the changelog.  I will do that.

As for a resource, check this out - https://github.com/skyajal/diypluginguide3.x

**Comment by h45rd** [comment]
Thanks a lot for the link.
Will go through the guide on the weekend :)

Renamed the script. Anything else I missed?

**Comment by ryecoaaron** [comment]
From a quick look, it looks good.  I will go ahead and merge it then test.  We can fix anything wrong in new commits.

**Comment by h45rd** [comment]
Thanks again for the help.
Will make sure my next pull request won't be such a mess :)

**Comment by ryecoaaron** [comment]
@h45rd I didn't think it was that bad and appreciate any help I can get :)

**Pull request merged**
